id: info
name: Information Phase
description: "Information gathering phase"
modules:
  - name: "nmap fast port checks"
    executable: "nmap"
    args: "-F --open -Pn "
    severity: 0
    positiveResponse:
      - "RE:22/tcp"
  - name: "whatweb high level info"
    executable: "whatweb"
    args: "-a 1 "
    severity: 0
    mode: print
  - name: "whatweb extended recon"
    executable: "whatweb"
    args: "-a 1 --plugins Adobe-Flash,Apache,AmazonElasticLoadBalancer,Day-Communique"
    severity: 0
    mode: print
  - name: "nmap waf fingerprint"
    executable: "nmap"
    args: "--script=/usr/app/nse/http-waf-fingerprint "
    severity: 0
    mode: filter
    positiveResponse:
      - "Detected WAF"
  - name: "nmap banner grabbing"
    executable: "nmap"
    args: "--script=/usr/app/nse/banner "
    severity: 0
    mode: print
    positiveResponse:
      - "RE:22/tcp"
      - "banner"
  - name: "nmap authentication finder"
    executable: "nmap"
    args: "--script=/usr/app/nse/http-auth-finder "
    severity: 0
    mode: print
  - name: "nmap backup finder"
    executable: "nmap"
    args: "--script=/usr/app/nse/backup-finder -maxdepth 3 "
    severity: 0
    mode: print
